config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :posts
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  belongs_to :user
  validates :date, :rationale, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, presence: true


  def full_name
    last_name.upcase + ", " + first_name.upcase
  end

end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin\
      user_type = current_user.try(:type)
      unless Admin.admin_types.include?(user_type)
        flash[:notice] = "You are not authorized to access this page."
        redirect_to root_path
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end

  private

  def self.admin_types
    ['AdminUser']
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:danger] = "You are not authorized to perform this action."
    redirect_to request.referrer || root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = current_user.posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
      flash[:success] = "Post successfully created!"
    else
      render :new
    end
  end

  def edit
    authorize @post
  end
  
  def update
    authorize @post
    
    if @post.update(post_params)
      redirect_to @post
      flash[:success] = "Post successfully updated!"
    else 
      render :edit
    end
  end

  def show
  end

  def destroy
    if @post.delete
      redirect_to posts_path
      flash[:success] = "Post successfully deleted!"
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
      :date, 
      :rationale,
      :user_id)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def homepage
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/application/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <a href="<%= polymorphic_path([namespace, resource]) -%>"
               class="action-show"
               >
              <%= render_field attribute %>
            </a>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) %></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/application/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(page.resource.errors.count, "error") %>
        prohibited this <%= page.resource_name %> from being saved:
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/application/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "#{t("administrate.actions.edit")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      "Back",
#      "#{t("administrate.actions.show")} #{page.page_title}",
      [namespace, page.resource],
      class: "button",
    ) if valid_action? :show %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/application/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      "#{t("administrate.actions.new")} #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action? :new %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/application/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "#{t("administrate.actions.new")} #{page.resource_name.titleize}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/application/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { "#{t("administrate.actions.show")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      "#{t("administrate.actions.edit")} #{page.resource.class}",
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action? :edit %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute %></dd>
    <% end %>
  </dl>
</section>

app/views/fields/enum_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.select field.attribute, field.select_field_values(f) %>
</div>

app/views/fields/enum_field/_index.html.erb
<%= field.to_s %>

app/views/fields/enum_field/_show.html.erb
<%= field.to_s %>

app/views/fields/password_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.password_field field.attribute %>
</div>

app/views/fields/password_field/_index.html.erb
<%#= field.to_s %>

app/views/fields/password_field/_show.html.erb
<%#= field.to_s %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtime</title>
    <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render 'shared/flashes' %> 
      <%= render 'shared/header' %>
      
      <main role="main">
        <%= yield %>
      </main>
      
      <%= render 'shared/footer' %>
    </div> <!-- /container -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true, class: "form-horizontal" do |f| %>
  <% if @post.errors.any? %>
    <%= render 'shared/errors', object: @post %>
  <% end %>
  <div class="form-group">
    <%= f.label :date, class: "col-2 col-form-label" %>	  
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rationale, class: "col-2 col-form-label" %>	  
    <%= f.text_area :rationale, class: "form-control" %>
  </div>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
  <tr>
    <th scope="row"><%= post.id %></th>
    <td><%= post.date %></td>
    <td><%= post.user.full_name %></td>
    <td><%= truncate(post.rationale) %></td>
    <td><%= link_to 'Edit', edit_post_path(post), id: "edit_#{post.id}" %></td>
    <td><%= link_to 'Delete', post_path(post), method: :delete, id: "delete_post_#{post.id}", data: { confirm: "Are you sure?" } %></td>
  </tr>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Last Name</th>
      <th scope="col">Rationale</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Entry #<%= "#{@post.id}" %></h1>

<p>Entry date: <%= @post.date %></p>
<p>Rationale: <%= @post.rationale %></p>
<p>Status: <%= @post.status %></p>

<%= link_to "My Entries", posts_path, class: "btn btn-primary" %>

app/views/shared/_errors.html.erb
<section id="errors">
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">Oops! The <%= object.class.name.humanize.downcase %> could not be saved.</h4>
  <p>Please correct the following <%= pluralize(object.errors.count, "error") %></p>
  <hr>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
</section>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="row">
    <div class="col">
      <div class="<%= "alert alert-#{key}" %>">
        <%= content_tag(:span, value) %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p>&copy; Overtime 2020</p>
</footer>

app/views/shared/_header.html.erb
<header class="header clearfix">
  <h3 class="text-muted">Overtime</h3>
  <nav>
    <div class="dropdown show float-right">
      <% if user_signed_in? %>
      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.full_name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <% if current_user.type == "AdminUser" %>
          <%= link_to "Dashboard", admin_root_path, class: "dropdown-item" %>
        <% end %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "nav-link #{active?(new_user_session_path)}" %>
      <% end %>
    </div>

    <ul class="nav nav-pills">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link #{active?(root_path)}" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "My Entries", posts_path, class: "nav-link #{active?(posts_path)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Entry", new_post_path, class: "nav-link #{active?(new_post_path)}" %>
      </li>
      <% end %>
    </ul>
  </nav>
</header>